FROM java:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/simple-microservice-0.0.1-SNAPSHOT-standalone.jar /simple-microservice/app.jar

EXPOSE 8080

CMD ["java", "-jar", "/simple-microservice/app.jar"]
